services:
  app:
    build:
      context: .docker/php_apache
    container_name: ${APP_NAME:-laravel}_app
    restart: unless-stopped
    ports:
      - ${APP_PORT:-80}:80
      - ${VITE_PORT:-5173}:5173
    volumes:
      - ./project:/var/www/project
